// <auto-generated />
using CarDealership.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDealership.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250317203730_AddCarModelsTable")]
    partial class AddCarModelsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarDealership.Models.CarMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarMakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("CarDealership.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarMakeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarMakeId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarMakeId = 1,
                            Engine = "1.5L 4-cylinder",
                            Name = "Equinox",
                            Trim = "RS"
                        },
                        new
                        {
                            Id = 2,
                            CarMakeId = 1,
                            Engine = "1.5L 4-cylinder",
                            Name = "Equinox",
                            Trim = "Activ"
                        },
                        new
                        {
                            Id = 3,
                            CarMakeId = 1,
                            Engine = "1.5L 4-cylinder",
                            Name = "Equinox",
                            Trim = "LT"
                        },
                        new
                        {
                            Id = 4,
                            CarMakeId = 1,
                            Engine = "TurboMax",
                            Name = "Silverado 1500",
                            Trim = "RST"
                        },
                        new
                        {
                            Id = 5,
                            CarMakeId = 1,
                            Engine = "5.3L V8",
                            Name = "Silverado 1500",
                            Trim = "Trail Boss"
                        },
                        new
                        {
                            Id = 6,
                            CarMakeId = 1,
                            Engine = "TurboMax",
                            Name = "Silverado 1500",
                            Trim = "LT"
                        });
                });

            modelBuilder.Entity("CarDealership.Models.CarModel", b =>
                {
                    b.HasOne("CarDealership.Models.CarMake", "CarMake")
                        .WithMany()
                        .HasForeignKey("CarMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarMake");
                });
#pragma warning restore 612, 618
        }
    }
}
