// <auto-generated />
using CarDealership.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDealership.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250317223229_AddCarTableAndData")]
    partial class AddCarTableAndData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarDealership.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drivetrain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MSRP")
                        .HasColumnType("int");

                    b.Property<int>("Miles")
                        .HasColumnType("int");

                    b.Property<int>("OurPrice")
                        .HasColumnType("int");

                    b.Property<string>("StockNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Used")
                        .HasColumnType("bit");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 1,
                            Color = "Black",
                            Drivetrain = "AWD",
                            MSRP = 33000,
                            Miles = 2,
                            OurPrice = 32000,
                            StockNumber = "25-1000",
                            VIN = "EQ251200",
                            Year = "2025"
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 3,
                            Color = "Silver",
                            Drivetrain = "FWD",
                            MSRP = 28000,
                            Miles = 3,
                            OurPrice = 26000,
                            StockNumber = "25-3000",
                            VIN = "EQ253200",
                            Year = "2025"
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 3,
                            Color = "White",
                            Drivetrain = "FWD",
                            MSRP = 28000,
                            Miles = 2,
                            OurPrice = 26000,
                            StockNumber = "25-3100",
                            VIN = "EQ254200",
                            Year = "2025"
                        });
                });

            modelBuilder.Entity("CarDealership.Models.CarMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarMakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("CarDealership.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarMakeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarMakeId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarMakeId = 1,
                            Engine = "1.5L 4-cylinder",
                            Name = "Equinox",
                            Trim = "RS"
                        },
                        new
                        {
                            Id = 2,
                            CarMakeId = 1,
                            Engine = "1.5L 4-cylinder",
                            Name = "Equinox",
                            Trim = "Activ"
                        },
                        new
                        {
                            Id = 3,
                            CarMakeId = 1,
                            Engine = "1.5L 4-cylinder",
                            Name = "Equinox",
                            Trim = "LT"
                        },
                        new
                        {
                            Id = 4,
                            CarMakeId = 1,
                            Engine = "TurboMax",
                            Name = "Silverado 1500",
                            Trim = "RST"
                        },
                        new
                        {
                            Id = 5,
                            CarMakeId = 1,
                            Engine = "5.3L V8",
                            Name = "Silverado 1500",
                            Trim = "Trail Boss"
                        },
                        new
                        {
                            Id = 6,
                            CarMakeId = 1,
                            Engine = "TurboMax",
                            Name = "Silverado 1500",
                            Trim = "LT"
                        });
                });

            modelBuilder.Entity("CarDealership.Models.Car", b =>
                {
                    b.HasOne("CarDealership.Models.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("CarDealership.Models.CarModel", b =>
                {
                    b.HasOne("CarDealership.Models.CarMake", "CarMake")
                        .WithMany()
                        .HasForeignKey("CarMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarMake");
                });
#pragma warning restore 612, 618
        }
    }
}
